import streamlit as st
import pandas as pd
import os
import glob
from pathlib import Path
from PIL import Image

# Setup paths
PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data" / "synthetic"
RESULTS_DIR = PROJECT_ROOT / "models" / "results"
FIGURES_DIR = PROJECT_ROOT / "outputs" / "figures"
POLLUTANTS = ['PM2.5', 'PM10', 'NO2', 'CO']

# Helpers
def load_csv(path):
    if os.path.exists(path):
        return pd.read_csv(path)
    return None

def main():
    # Configure page
    st.set_page_config(
        page_title="Vehicular Pollution Estimation Pipeline Dashboard",
        page_icon="🌍",
        layout="wide"
    )

    st.sidebar.title("Navigation")
    page = st.sidebar.radio("Go to:", [
        "Overview & Run Pipeline", 
        "Data Explorer", 
        "Model Evaluation Metrics", 
        "Visualizations"
    ])

    if page == "Overview & Run Pipeline":
        st.title("🌍 Vehicular Pollution Estimation Dashboard")
        st.markdown("""
        This dashboard visualizes the data, evaluation metrics, and plots generated by the **Vehicular Pollution Estimation pipeline**.
        """)
        
        # Display Key Numerical Values
        st.subheader("📊 Key Numerical Metrics (Best R² per Pollutant)")
        metrics_cols = st.columns(len(POLLUTANTS))
        for i, pollutant in enumerate(POLLUTANTS):
            with metrics_cols[i]:
                comp_path = RESULTS_DIR / pollutant / "model_comparison.csv"
                comp_df = load_csv(comp_path)
                if comp_df is not None:
                    # Display the max R2 and the model that achieved it
                    best_row = comp_df.loc[comp_df['Test_R2'].idxmax()]
                    st.metric(label=f"{pollutant} ({best_row['Model']})", 
                              value=f"{best_row['Test_R2']:.4f}", 
                              delta=f"RMSE: {best_row['Test_RMSE']:.4f}",
                              delta_color="off")
                else:
                    st.metric(label=f"{pollutant} Data", value="Not Run")
                    
        st.divider()

        # Display Graphs
        st.subheader("🖼️ Global Performance Graphs")
        vis_col1, vis_col2 = st.columns(2)
        r2_path = FIGURES_DIR / "all_pollutants_comparison_R2.png"
        rmse_path = FIGURES_DIR / "all_pollutants_comparison_RMSE.png"
        
        figs_found = False
        with vis_col1:
            if os.path.exists(r2_path):
                st.image(Image.open(r2_path), caption="Cross-Pollutant R² Comparison", use_column_width=True)
                figs_found = True
        with vis_col2:
            if os.path.exists(rmse_path):
                st.image(Image.open(rmse_path), caption="Cross-Pollutant RMSE Comparison", use_column_width=True)
                figs_found = True
                
        if not figs_found:
            st.info("No global graphs generated yet. Please run the pipeline.")

        st.divider()

        st.markdown("""
        ### How to generate results?
        If you haven't fully run the pipeline yet, you need to run it to generate the complete data for this dashboard.
        Run the following command in your terminal:
        ```bash
        python main.py --mode full --no-tune
        ```
        *(Note: `--no-tune` makes it run much faster by skipping hyperparameter tuning)*
        """)

    elif page == "Data Explorer":
        st.title("📊 Synthetic Data Explorer")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Traffic Data")
            traffic_path = DATA_DIR / "synthetic_traffic_data.csv"
            traffic_df = load_csv(traffic_path)
            if traffic_df is not None:
                # Add month column
                traffic_df['timestamp'] = pd.to_datetime(traffic_df['timestamp'])
                traffic_df['month'] = traffic_df['timestamp'].dt.month
                traffic_df['month_name'] = traffic_df['timestamp'].dt.strftime('%B')
                
                st.dataframe(traffic_df.head(100))
                st.caption(f"Total records: {len(traffic_df)}")
            else:
                st.warning(f"File not found: {traffic_path}")
                traffic_df = None
                
        with col2:
            st.subheader("Pollution Data")
            pollution_path = DATA_DIR / "synthetic_pollution_data.csv"
            pollution_df = load_csv(pollution_path)
            if pollution_df is not None:
                # Add month column
                pollution_df['timestamp'] = pd.to_datetime(pollution_df['timestamp'])
                pollution_df['month'] = pollution_df['timestamp'].dt.month
                pollution_df['month_name'] = pollution_df['timestamp'].dt.strftime('%B')
                
                st.dataframe(pollution_df.head(100))
                st.caption(f"Total records: {len(pollution_df)}")
            else:
                st.warning(f"File not found: {pollution_path}")
                pollution_df = None
        
        st.divider()
        
        # Plotting section
        st.subheader("📈 Data Visualization")
        
        plot_type = st.radio("Select Data to Plot:", ["Traffic Data", "Pollution Data"], horizontal=True)
        
        if plot_type == "Traffic Data" and traffic_df is not None:
            st.markdown("**Traffic Data Plots**")
            
            # Get numeric columns (exclude timestamp and month columns)
            numeric_cols = traffic_df.select_dtypes(include=['number']).columns.tolist()
            numeric_cols = [col for col in numeric_cols if col not in ['month']]
            
            plot_choice = st.multiselect(
                "Select columns to plot:",
                numeric_cols,
                default=numeric_cols[:2] if len(numeric_cols) > 0 else []
            )
            
            if plot_choice:
                # Option to group by month
                group_by_month = st.checkbox("Group by Month", value=False)
                
                if group_by_month:
                    # Create monthly aggregation
                    monthly_data = traffic_df.groupby('month_name')[plot_choice].mean()
                    st.line_chart(monthly_data)
                else:
                    # Plot raw time series
                    st.line_chart(traffic_df.set_index('timestamp')[plot_choice])
                    
        elif plot_type == "Pollution Data" and pollution_df is not None:
            st.markdown("**Pollution Data Plots**")
            
            # Get numeric columns (exclude timestamp and month columns)
            numeric_cols = pollution_df.select_dtypes(include=['number']).columns.tolist()
            numeric_cols = [col for col in numeric_cols if col not in ['month']]
            
            plot_choice = st.multiselect(
                "Select columns to plot:",
                numeric_cols,
                default=numeric_cols[:2] if len(numeric_cols) > 0 else []
            )
            
            if plot_choice:
                # Option to group by month
                group_by_month = st.checkbox("Group by Month", value=False)
                
                if group_by_month:
                    # Create monthly aggregation
                    monthly_data = pollution_df.groupby('month_name')[plot_choice].mean()
                    st.line_chart(monthly_data)
                else:
                    # Plot raw time series
                    st.line_chart(pollution_df.set_index('timestamp')[plot_choice])

    elif page == "Model Evaluation Metrics":
        st.title("📈 Model Evaluation Metrics")
        st.markdown("Compare the performance of different models across pollutants.")
        
        tabs = st.tabs(POLLUTANTS)
        
        for i, pollutant in enumerate(POLLUTANTS):
            with tabs[i]:
                st.subheader(f"{pollutant} Model Comparison")
                comp_path = RESULTS_DIR / pollutant / "model_comparison.csv"
                comp_df = load_csv(comp_path)
                
                if comp_df is not None:
                    st.dataframe(comp_df.style.highlight_max(subset=['Test_R2'], color='lightgreen')
                                               .highlight_min(subset=['Test_RMSE'], color='lightgreen'))
                else:
                    st.warning(f"Model comparison not found for {pollutant}. Pipeline may not have finished.")

    elif page == "Visualizations":
        st.title("🖼️ Output Visualizations")
        
        # 1. Global comparisons
        st.subheader("Global Comparisons")
        col1, col2 = st.columns(2)
        with col1:
            r2_path = FIGURES_DIR / "all_pollutants_comparison_R2.png"
            if os.path.exists(r2_path):
                st.image(Image.open(r2_path), caption="Cross-Pollutant R² Comparison")
        with col2:
            rmse_path = FIGURES_DIR / "all_pollutants_comparison_RMSE.png"
            if os.path.exists(rmse_path):
                st.image(Image.open(rmse_path), caption="Cross-Pollutant RMSE Comparison")
                
        st.divider()
                
        # 2. Pollutant specific
        st.subheader("Pollutant-Specific Visualizations")
        selected_pollutant = st.selectbox("Select Pollutant:", POLLUTANTS)
        
        pollutant_fig_dir = FIGURES_DIR / selected_pollutant
        if os.path.exists(pollutant_fig_dir):
            png_files = glob.glob(str(pollutant_fig_dir / "*.png"))
            if png_files:
                # Group by type loosely
                for img_path in sorted(png_files):
                    filename = os.path.basename(img_path)
                    st.image(Image.open(img_path), caption=filename)
            else:
                st.info(f"No visualization images found in {pollutant_fig_dir}")
        else:
            st.warning(f"Directory not found: {pollutant_fig_dir}. Pipeline may not have generated visualizations for {selected_pollutant}.")

if __name__ == "__main__":
    import sys
    try:
        from streamlit.web import cli as stcli
    except ImportError:
        # Older versions of Streamlit
        from streamlit import cli as stcli
        
    try:
        import streamlit.runtime as runtime
        if runtime.exists():
            main()
        else:
            sys.argv = ["streamlit", "run", sys.argv[0]]
            sys.exit(stcli.main())
    except ImportError:
        # For very old versions of Streamlit
        sys.argv = ["streamlit", "run", sys.argv[0]]
        sys.exit(stcli.main())
